"""
Controlled conversation events for YojanSetu State Machine transitions (Day 25).
"""

from enum import Enum


class ConversationEvent(str, Enum):
    """
    Events triggering deterministic state machine transitions.
    """
    SESSION_STARTED = "SESSION_STARTED"
    NEED_PROVIDED = "NEED_PROVIDED"
    PROFILE_VALUE_EXTRACTED = "PROFILE_VALUE_EXTRACTED"
    PROFILE_VALUE_EXTRACTED_CONFIRMATION_REQUIRED = "PROFILE_VALUE_EXTRACTED_CONFIRMATION_REQUIRED"
    PROFILE_VALUE_CONFIRMED = "PROFILE_VALUE_CONFIRMED"
    PROFILE_VALUE_REJECTED = "PROFILE_VALUE_REJECTED"
    PROFILE_VALUE_CORRECTED = "PROFILE_VALUE_CORRECTED"
    PROFILE_VALUE_UNKNOWN = "PROFILE_VALUE_UNKNOWN"
    PROFILE_VALUE_DECLINED = "PROFILE_VALUE_DECLINED"
    DISCOVERY_COMPLETED = "DISCOVERY_COMPLETED"
    ELIGIBLE_RESULTS_FOUND = "ELIGIBLE_RESULTS_FOUND"
    MORE_INFO_REQUIRED = "MORE_INFO_REQUIRED"
    NO_RESULTS_FOUND = "NO_RESULTS_FOUND"
    CANNOT_RESOLVE_MORE = "CANNOT_RESOLVE_MORE"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    CLARIFICATION_PROVIDED = "CLARIFICATION_PROVIDED"
    CITIZEN_QUERY_RECEIVED = "CITIZEN_QUERY_RECEIVED"
    QUERY_ANSWERED = "QUERY_ANSWERED"
    SCHEME_SELECTED = "SCHEME_SELECTED"
    START_OVER_REQUESTED = "START_OVER_REQUESTED"
    END_CONVERSATION_REQUESTED = "END_CONVERSATION_REQUESTED"
    CHANGE_NEED_REQUESTED = "CHANGE_NEED_REQUESTED"
    LANGUAGE_CHANGED = "LANGUAGE_CHANGED"
    REPEAT_REQUESTED = "REPEAT_REQUESTED"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    MAX_TURNS_REACHED = "MAX_TURNS_REACHED"
