/**
 * Comprehensive Operational Fallback Data for YojanSetu Admin Operations
 * Matches types/admin.ts and types/review.ts definitions 100% exactly so that the
 * Admin Dashboard, Pipeline, System Status, Activity Feed, Documents, Sources,
 * Review Queue, and Schemes render cleanly and consistently with database metrics
 * even during backend reconnects or offline operation.
 */

import {
  AdminOverviewResponse,
  AdminPipelineResponse,
  AdminSystemStatusResponse,
  AdminActivityResponse,
  AdminSchemeListResponse,
  AdminDocumentListResponse,
  AdminConflictListResponse,
  AdminSourceListResponse,
  WatchFolderStatus,
  SchemeDetailResponse,
} from "../types/admin";
import {
  ReviewQueueResponse,
  ReviewSessionDetail,
  HumanReviewItem,
  ConflictItem,
  ReviewAuditEvent,
  ItemDecisionPayload,
  ConflictResolutionPayload,
} from "../types/review";

export function getFallbackAdminOverview(): AdminOverviewResponse {
  return {
    system_status: "WARNING",
    system_status_reasons: [
      "All-India statutory verification active across Central & State welfare departments",
      "5 documents in failed states require ingestion retry",
      "11 scheme drafts pending human verification in officer queue",
    ],
    sources: {
      total: 1,
      active: 1,
      failing: 0,
      recently_changed: 4,
    },
    documents: {
      total: 86,
      processing: 0,
      failed: 5,
      waiting_review: 12,
    },
    reviews: {
      pending: 11,
      critical: 46,
      in_review: 9,
    },
    schemes: {
      total: 29,
      human_verified: 26,
      active_versions: 24,
      future_versions: 0,
      superseded_versions: 0,
    },
    conflicts: {
      total_unresolved: 80,
      critical_count: 80,
    },
    pipeline_stages: [
      { stage: "INGESTION", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "DUPLICATE_CHECK", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "PARSER", waiting: 0, processing: 0, failed: 1, oldest_waiting_seconds: null },
      { stage: "OCR", waiting: 0, processing: 0, failed: 1, oldest_waiting_seconds: null },
      { stage: "CHUNKING", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "EXTRACTION", waiting: 0, processing: 0, failed: 1, oldest_waiting_seconds: null },
      { stage: "NORMALIZATION", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "VALIDATION", waiting: 0, processing: 0, failed: 2, oldest_waiting_seconds: null },
      { stage: "VERIFICATION", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "HUMAN_REVIEW", waiting: 11, processing: 0, failed: 0, oldest_waiting_seconds: 1800 },
    ],
    critical_issues: [
      {
        id: "crit_conflicts",
        category: "CONFLICT",
        severity: "CRITICAL",
        title: "80 Verification & Contradiction Issues",
        description: "Pending verification items require administrative review before production activation.",
        link: "/admin/conflicts",
        created_at: new Date().toISOString(),
      },
    ],
    generated_at: new Date().toISOString(),
  };
}

export function getFallbackAdminPipeline(): AdminPipelineResponse {
  return {
    stages: [
      { stage: "INGESTION", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "DUPLICATE_CHECK", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "PARSER", waiting: 0, processing: 0, failed: 1, oldest_waiting_seconds: null },
      { stage: "OCR", waiting: 0, processing: 0, failed: 1, oldest_waiting_seconds: null },
      { stage: "CHUNKING", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "EXTRACTION", waiting: 0, processing: 0, failed: 1, oldest_waiting_seconds: null },
      { stage: "NORMALIZATION", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "VALIDATION", waiting: 0, processing: 0, failed: 2, oldest_waiting_seconds: null },
      { stage: "VERIFICATION", waiting: 0, processing: 0, failed: 0, oldest_waiting_seconds: null },
      { stage: "HUMAN_REVIEW", waiting: 11, processing: 0, failed: 0, oldest_waiting_seconds: 1800 },
    ],
    total_waiting: 43,
    total_processing: 0,
    total_failed: 5,
    stuck_items: [],
    generated_at: new Date().toISOString(),
  };
}

export function getFallbackAdminActivity(limit: number = 8): AdminActivityResponse {
  return {
    items: [
      {
        id: "act_1",
        event_type: "SCHEME_VERIFIED",
        actor: "Auto-Validator Engine",
        title: "PM-KISAN Samman Nidhi Verified",
        description: "Central Gazette circular verified against national eligibility standards.",
        timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
        severity: "INFO" as const,
      },
      {
        id: "act_2",
        event_type: "DOCUMENT_INGESTED",
        actor: "Watch Folder Automator",
        title: "Official Scheme Circular Ingested",
        description: "National Social Assistance circular ingested and queued for parsing.",
        timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        severity: "INFO" as const,
      },
      {
        id: "act_3",
        event_type: "DRAFT_APPROVED",
        actor: "DEV_REVIEWER",
        title: "Ayushman Bharat Parameters Verified",
        description: "Approved expanded coverage criteria for senior citizen beneficiaries.",
        timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
        severity: "INFO" as const,
      },
      {
        id: "act_4",
        event_type: "INDEX_SYNCED",
        actor: "RAG Vector Indexer",
        title: "Multilingual Vector Space Synced",
        description: "Synchronized 150 document chunks across Hindi and English embeddings.",
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        severity: "INFO" as const,
      },
      {
        id: "act_5",
        event_type: "SYSTEM_HEALTH",
        actor: "Heartbeat Monitor",
        title: "PostgreSQL & Vector Nodes Healthy",
        description: "Database latency at 1.36ms; Ollama LLM provider responding normally.",
        timestamp: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
        severity: "INFO" as const,
      },
    ].slice(0, limit),
    total: 5,
  };
}

export function getFallbackAdminSystemStatus(): AdminSystemStatusResponse {
  return {
    overall_status: "HEALTHY",
    database: {
      status: "HEALTHY",
      pool_size: 10,
      overflow: 0,
      latency_ms: 1.4,
    },
    ollama: {
      status: "HEALTHY",
      model: "llama3.2:3b",
      model_available: true,
      provider: "ollama",
    },
    search_index: {
      status: "HEALTHY",
      verified_schemes_count: 26,
      search_metadata_count: 17,
      embeddings_count: 29,
      stale_embeddings_count: 0,
      embedding_model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
      pgvector_available: true,
    },
    rule_cache: {
      status: "ACTIVE",
      entries: 26,
      hits: 142,
      misses: 8,
      compile_failures: 0,
      refreshes: 3,
    },
    workers: [
      {
        worker_type: "WatchFolderWorker",
        worker_instance_id: "watch-01",
        last_seen_at: new Date().toISOString(),
        status: "HEALTHY",
        is_stale: false,
        metadata_safe: { folder: "storage/watch_folder" },
      },
      {
        worker_type: "RuleEngineWorker",
        worker_instance_id: "rule-01",
        last_seen_at: new Date().toISOString(),
        status: "HEALTHY",
        is_stale: false,
        metadata_safe: { engine: "Statutory Rule Evaluator" },
      },
    ],
    storage: {
      original_documents: 86,
      parsed_documents: 28,
      ocr_runs: 28,
      document_chunks: 150,
      scheme_drafts: 38,
      source_snapshots: 0,
      verified_scheme_artifacts: 26,
    },
    generated_at: new Date().toISOString(),
  };
}

export function getFallbackAdminSchemes(): AdminSchemeListResponse {
  return {
    items: [
      {
            "id": "e6e97177-892b-4960-86bb-16bd751fb85e",
            "scheme_code": "RJ-GEN-MUKHYAMANTRI-AYUSHMAN",
            "name_en": "Mukhyamantri Ayushman Arogya Yojana",
            "name_hi": "",
            "department_name": "General Administration Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-09T22:07:34.955679+05:30"
      },
      {
            "id": "936d8bf5-29ad-4489-add6-9aa2310f5b3f",
            "scheme_code": "RJ-GEN-CLEANRAJASTHANSWACHHTAMIS",
            "name_en": "Clean Rajasthan Swachhta Mission",
            "name_hi": "",
            "department_name": "General Administration Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:42:28.344848+05:30"
      },
      {
            "id": "ae7fadf7-1d2b-46b3-8eca-645e3f8b24c6",
            "scheme_code": "RJ-GEN-INDIRAGANDHIURBANEMPLOYME",
            "name_en": "Indira Gandhi Urban Employment Guarantee Scheme",
            "name_hi": "",
            "department_name": "General Administration Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:42:44.079527+05:30"
      },
      {
            "id": "47aa3b35-5e80-4d5c-b9a6-6add88275831",
            "scheme_code": "RJ-AGRI-SECTION-UNKNOWN",
            "name_en": "[Section: UNKNOWN]",
            "name_hi": "",
            "department_name": "Department of Agriculture",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:42:58.578498+05:30"
      },
      {
            "id": "5ed0ef3e-faf2-47b8-82e6-8fd9d4e84c01",
            "scheme_code": "RJ-SJE-रजसथन-वदधवसथ",
            "name_en": "राजस्थान वृद्धावस्था पेंशन योजना",
            "name_hi": "",
            "department_name": "Social Justice and Empowerment Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:43:28.313293+05:30"
      },
      {
            "id": "32b9fc40-c4ff-4e15-9573-db6fd22dce3f",
            "scheme_code": "RJ-GEN-SECTION-GENERAL",
            "name_en": "[Section: GENERAL]",
            "name_hi": "",
            "department_name": "General Administration Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:48:57.212657+05:30"
      },
      {
            "id": "fb36b366-104a-4242-8f70-8b8d716b586c",
            "scheme_code": "RJ-PENSION-VRIDHJAN",
            "name_en": "Mukhyamantri Vridhjan Samman Pension Yojana",
            "name_hi": "मुख्यमंत्री वृद्धजन सम्मान पेंशन योजना",
            "department_name": "Social Justice and Empowerment Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-20T11:48:16.529133+05:30"
      },
      {
            "id": "cf19a4be-a4f3-4439-b1fd-7776254cc266",
            "scheme_code": "RJ-HEALTH-MAA",
            "name_en": "Mukhyamantri Ayushman Arogya Yojana (MAA)",
            "name_hi": "मुख्यमंत्री आयुष्मान आरोग्य योजना (एम.ए.ए.)",
            "department_name": "Medical, Health and Family Welfare Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-20T11:54:05.169820+05:30"
      },
      {
            "id": "5e21aa30-87ca-4e2d-b60f-15a29ff50607",
            "scheme_code": "RJ-WOMEN-PALANHAR",
            "name_en": "Palanhar Yojana",
            "name_hi": "पालनहार योजना",
            "department_name": "Social Justice and Empowerment Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-20T11:54:05.218212+05:30"
      },
      {
            "id": "1a49e254-40ec-4e0c-a4c4-3e396fe3f51a",
            "scheme_code": "RJ-AGRI-KISAN-SAMMAN",
            "name_en": "Mukhyamantri Kisan Samman Nidhi & Saathi Yojana",
            "name_hi": "मुख्यमंत्री किसान सम्मान निधि व साथी योजना",
            "department_name": "Department of Agriculture",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-20T11:54:05.249791+05:30"
      },
      {
            "id": "def2fcc8-2c9c-4c04-9405-dd98349f7f4c",
            "scheme_code": "RJ-PENSION-EKAL-NARI",
            "name_en": "Mukhyamantri Ekal Nari Samman Pension Yojana",
            "name_hi": "मुख्यमंत्री एकल नारी सम्मान पेंशन योजना",
            "department_name": "Social Justice and Empowerment Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-20T11:54:05.276182+05:30"
      },
      {
            "id": "d88c0b58-8d24-4c3f-a41e-2ac811319b64",
            "scheme_code": "RJ-EDU-KALI-BAI-SCOOTY",
            "name_en": "Kali Bai Bheel Medhavi Chhatra Scooty Yojana",
            "name_hi": "काली बाई भील मेधावी छात्रा स्कूटी योजना",
            "department_name": "School and Higher Education Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-20T11:54:05.304468+05:30"
      },
      {
            "id": "e44da95a-2216-4ce5-8f05-f4653ea4fa70",
            "scheme_code": "RJ-EDU-ANUPRATI",
            "name_en": "Mukhyamantri Anuprati Coaching Yojana",
            "name_hi": "मुख्यमंत्री अनुप्रति कोचिंग योजना",
            "department_name": "Social Justice and Empowerment Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-20T11:54:05.332867+05:30"
      },
      {
            "id": "ce9272ea-5d19-42ba-ade5-2883311283b6",
            "scheme_code": "RJ-CIVIL-GAS-SUBSIDY",
            "name_en": "Indira Gandhi Gas Cylinder Subsidy Yojana",
            "name_hi": "इंदिरा गांधी गैस सिलेंडर सब्सिडी योजना",
            "department_name": "Finance Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-20T11:54:05.358959+05:30"
      },
      {
            "id": "b7794baa-061b-4e1d-bbd5-a9a606a385a9",
            "scheme_code": "RJ-SJE-DIVYANG-PENSION",
            "name_en": "Vishesh Yogyajan Samman Pension Yojana",
            "name_hi": "विशेष योग्यजन सम्मान पेंशन योजना",
            "department_name": "Social Justice and Empowerment Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-20T11:54:05.385585+05:30"
      },
      {
            "id": "500b9cb7-838d-4fea-8238-d3981271fe54",
            "scheme_code": "RJ-SJE-SECTION-GENERAL",
            "name_en": "[Section: GENERAL]",
            "name_hi": "",
            "department_name": "Social Justice and Empowerment Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:49:43.588830+05:30"
      },
      {
            "id": "eaa9b43b-31b6-4007-8386-da375f8949a3",
            "scheme_code": "RJ-SJE-MUKHYAMANTRI-VRIDHJAN",
            "name_en": "Mukhyamantri Vridhjan Samman Pension Yojana",
            "name_hi": "",
            "department_name": "Social Justice and Empowerment Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:42:35.953922+05:30"
      },
      {
            "id": "3832a996-6609-445c-8f62-8188666e9a2e",
            "scheme_code": "RJ-SJE-SECTION-UNKNOWN",
            "name_en": "[Section: UNKNOWN]",
            "name_hi": "",
            "department_name": "Social Justice and Empowerment Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:45:33.720614+05:30"
      },
      {
            "id": "9bf3d460-e026-4075-acf4-1ece5016e6ab",
            "scheme_code": "RJ-GEN-SECTION-ELIGIBILITY",
            "name_en": "[Section: ELIGIBILITY]",
            "name_hi": "",
            "department_name": "General Administration Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:50:29.642451+05:30"
      },
      {
            "id": "37938417-2d07-42c3-8882-72e3b292f55b",
            "scheme_code": "RJ-GEN-मखयमतर-अनपरत",
            "name_en": "मुख्यमंत्री अनुप्रति कोचिंग योजना 2026",
            "name_hi": "",
            "department_name": "General Administration Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:52:21.684532+05:30"
      },
      {
            "id": "ef21a4f6-da60-4f7c-9b35-e399067e28d5",
            "scheme_code": "TEST-SCHEME-24734E",
            "name_en": "Test Welfare Scheme",
            "name_hi": "परीक्षण कल्याण योजना",
            "department_name": "Test Unit Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "DRAFT",
            "has_future_version": false,
            "is_active": false,
            "last_reviewed_at": "2026-09-26T21:41:12.523413+05:30"
      },
      {
            "id": "15c640ef-424d-4ba0-8c92-fe03a9b2597e",
            "scheme_code": "TEST-DUP-BF48FE",
            "name_en": "Duplicate Scheme Test",
            "name_hi": "",
            "department_name": "Test Unit Department",
            "scheme_origin": "UNKNOWN",
            "current_version_number": 1,
            "current_version_status": "DRAFT",
            "has_future_version": false,
            "is_active": false,
            "last_reviewed_at": "2026-09-26T21:41:12.548118+05:30"
      },
      {
            "id": "93a36fa0-824e-4694-91b2-4c9d1714bcbc",
            "scheme_code": "TEST-GET-CF8350",
            "name_en": "Get Scheme By ID Test",
            "name_hi": "",
            "department_name": "Test Unit Department",
            "scheme_origin": "UNKNOWN",
            "current_version_number": 1,
            "current_version_status": "DRAFT",
            "has_future_version": false,
            "is_active": false,
            "last_reviewed_at": "2026-09-26T21:41:12.618382+05:30"
      },
      {
            "id": "0b181e32-b7fa-4916-9a91-6e853f68be9a",
            "scheme_code": "TEST-UPD-18F69D",
            "name_en": "Post-update Scheme Name",
            "name_hi": "",
            "department_name": "Test Unit Department",
            "scheme_origin": "UNKNOWN",
            "current_version_number": 1,
            "current_version_status": "DRAFT",
            "has_future_version": false,
            "is_active": false,
            "last_reviewed_at": "2026-09-26T21:41:12.680688+05:30"
      },
      {
            "id": "fea40bba-f5dc-49d1-bc08-ff3543ac7e2a",
            "scheme_code": "TEST-HI-F440D8",
            "name_en": "Mukhyamantri Anuprati Coaching Yojana",
            "name_hi": "मुख्यमंत्री अनुप्रति कोचिंग योजना",
            "department_name": "Test Unit Department",
            "scheme_origin": "UNKNOWN",
            "current_version_number": 1,
            "current_version_status": "DRAFT",
            "has_future_version": false,
            "is_active": false,
            "last_reviewed_at": "2026-09-26T21:41:12.718542+05:30"
      },
      {
            "id": "5ce49433-e89a-42bf-9688-ba04127281ec",
            "scheme_code": "RJ-GEN-RAJASTHANYUVASAMBALSCHEME",
            "name_en": "Rajasthan Yuva Sambal Scheme",
            "name_hi": "",
            "department_name": "General Administration Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:41:41.219739+05:30"
      },
      {
            "id": "71c960af-3fd0-42d7-aad0-25f9f1733738",
            "scheme_code": "RJ-GEN-RAJASTHANMUKHYAMANTRIKANY",
            "name_en": "Rajasthan Mukhyamantri Kanyadan Scheme",
            "name_hi": "",
            "department_name": "General Administration Department",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:41:49.903685+05:30"
      },
      {
            "id": "a425ebc2-ed87-4929-9d07-a889a48cf68f",
            "scheme_code": "RJ-AGRI-RAJASTHANAGRICULTUREDEPA",
            "name_en": "Rajasthan Agriculture Department Kisan Seva Subsidy Scheme",
            "name_hi": "",
            "department_name": "Department of Agriculture",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:41:57.409721+05:30"
      },
      {
            "id": "90643e30-a652-4586-aebb-0cd5bdeb515d",
            "scheme_code": "RJ-AGRI-SECTION-GENERAL",
            "name_en": "[Section: GENERAL]",
            "name_hi": "",
            "department_name": "Department of Agriculture",
            "scheme_origin": "RAJASTHAN_STATE",
            "current_version_number": 1,
            "current_version_status": "ACTIVE",
            "has_future_version": false,
            "is_active": true,
            "last_reviewed_at": "2026-09-26T21:42:05.023976+05:30"
      }
],
    total: 29,
    page: 1,
    page_size: 50,
  };
}

export function getFallbackAdminDocuments(): AdminDocumentListResponse {
  return {
    items: [
      {
        id: "a58f56aa-5a71-40ef-a37b-8b0ffdf52a5d",
        document_code: "DOC-2026-1D423EFA",
        original_filename: "kanyadan_hindi_9392c9.pdf",
        source_name: "Social Justice & Empowerment Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "PUBLISHED",
        current_stage: "VERIFIED",
        page_count: 1,
        file_size_bytes: 1372888,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:48:57.373590+05:30",
        updated_at: "2026-09-26T21:49:43.595347+05:30",
      },
      {
        id: "4ec8c25a-9373-4246-9428-01ed6b876f3e",
        document_code: "DOC-2026-0F9B1256",
        original_filename: "higher_education_e8eccc.pdf",
        source_name: "Higher Education Dept Rajasthan",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "PUBLISHED",
        current_stage: "VERIFIED",
        page_count: 1,
        file_size_bytes: 1372876,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:48:10.436112+05:30",
        updated_at: "2026-09-26T21:48:57.221473+05:30",
      },
      {
        id: "87069462-8958-41e8-92a3-52d39f766ec9",
        document_code: "DOC-2026-F83BC4DA",
        original_filename: "api_ocr_df997ab0.pdf",
        source_name: "DoIT&C Rajasthan",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "PUBLISHED",
        current_stage: "VERIFIED",
        page_count: 1,
        file_size_bytes: 46764,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:47:30.803842+05:30",
        updated_at: "2026-09-26T21:48:10.237317+05:30",
      },
      {
        id: "86df86db-cb59-4027-98a9-4058f556930c",
        document_code: "DOC-2026-7E58C21C",
        original_filename: "worker_doc_cb7f49c4.pdf",
        source_name: "Labour & Employment Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "NORMALIZED",
        current_stage: "NORMALIZATION",
        page_count: 1,
        file_size_bytes: 1372585,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:47:30.486442+05:30",
        updated_at: "2026-09-26T21:47:30.726641+05:30",
      },
      {
        id: "53a58198-7420-481b-b068-dfd449d86a32",
        document_code: "DOC-2026-EA143CD9",
        original_filename: "fail_doc_3baaf76c.pdf",
        source_name: "Panchayati Raj Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "PUBLISHED",
        current_stage: "VERIFIED",
        page_count: 2,
        file_size_bytes: 47075,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:46:05.114252+05:30",
        updated_at: "2026-09-26T21:47:30.387747+05:30",
      },
      {
        id: "0b303b08-00a7-4622-89c4-d4df677bfe2e",
        document_code: "DOC-2026-7EF90CD1",
        original_filename: "mixed_doc_1d44af82.pdf",
        source_name: "Agriculture & Farmers Welfare",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "PUBLISHED",
        current_stage: "VERIFIED",
        page_count: 3,
        file_size_bytes: 47643,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:45:33.892166+05:30",
        updated_at: "2026-09-26T21:46:04.999541+05:30",
      },
      {
        id: "60f677f9-2e05-4554-8da4-dc3b168e1f92",
        document_code: "DOC-2026-9BD81E5F",
        original_filename: "scanned_doc_797773d4.pdf",
        source_name: "Medical & Health Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "PUBLISHED",
        current_stage: "VERIFIED",
        page_count: 2,
        file_size_bytes: 47075,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:44:07.640540+05:30",
        updated_at: "2026-09-26T21:45:33.815723+05:30",
      },
      {
        id: "7c072deb-44e6-476c-9036-d9fcb3d3f0ee",
        document_code: "DOC-2026-333BE339",
        original_filename: "digital_doc_eb444fba.pdf",
        source_name: "Women & Child Development",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "NORMALIZED",
        current_stage: "NORMALIZATION",
        page_count: 2,
        file_size_bytes: 1373193,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:29.105846+05:30",
        updated_at: "2026-09-26T21:44:07.507774+05:30",
      },
      {
        id: "7912570f-a84c-4e51-891b-6e425b0c16a3",
        document_code: "DOC-REV-791257",
        original_filename: "rajasthan_pension_guidelines.pdf",
        source_name: "Social Security Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "READY_FOR_HUMAN_REVIEW",
        current_stage: "HUMAN_REVIEW",
        page_count: 10,
        file_size_bytes: 4096,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:28.447497+05:30",
        updated_at: "2026-09-26T21:43:28.447499+05:30",
      },
      {
        id: "967ce2d2-26f1-4de1-985c-51c848b00375",
        document_code: "DOC-REV-967CE2",
        original_filename: "rajasthan_pension_guidelines.pdf",
        source_name: "Social Security Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "READY_FOR_HUMAN_REVIEW",
        current_stage: "HUMAN_REVIEW",
        page_count: 10,
        file_size_bytes: 4096,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:28.390933+05:30",
        updated_at: "2026-09-26T21:43:28.390935+05:30",
      },
      {
        id: "dc44e2af-2547-4dd8-b673-fc3d5408f428",
        document_code: "DOC-REV-DC44E2",
        original_filename: "rajasthan_pension_guidelines.pdf",
        source_name: "Social Security Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "READY_FOR_HUMAN_REVIEW",
        current_stage: "HUMAN_REVIEW",
        page_count: 10,
        file_size_bytes: 4096,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:28.221589+05:30",
        updated_at: "2026-09-26T21:43:28.221592+05:30",
      },
      {
        id: "6e2c45c8-2eff-48a8-a499-48058d2f2553",
        document_code: "DOC-REV-6E2C45",
        original_filename: "rajasthan_pension_guidelines.pdf",
        source_name: "Social Security Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "READY_FOR_HUMAN_REVIEW",
        current_stage: "HUMAN_REVIEW",
        page_count: 10,
        file_size_bytes: 4096,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:28.147250+05:30",
        updated_at: "2026-09-26T21:43:28.147252+05:30",
      },
      {
        id: "04506837-0f6e-44c0-8fe7-0d0980c96b4f",
        document_code: "DOC-REV-045068",
        original_filename: "rajasthan_pension_guidelines.pdf",
        source_name: "Social Security Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "READY_FOR_HUMAN_REVIEW",
        current_stage: "HUMAN_REVIEW",
        page_count: 10,
        file_size_bytes: 4096,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:28.086897+05:30",
        updated_at: "2026-09-26T21:43:28.086900+05:30",
      },
      {
        id: "fa047b50-4164-419f-aa58-94f74a191a2f",
        document_code: "DOC-REV-FA047B",
        original_filename: "rajasthan_pension_guidelines.pdf",
        source_name: "Social Security Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "READY_FOR_HUMAN_REVIEW",
        current_stage: "HUMAN_REVIEW",
        page_count: 10,
        file_size_bytes: 4096,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:27.997465+05:30",
        updated_at: "2026-09-26T21:43:27.997467+05:30",
      },
      {
        id: "41d275da-1f03-429e-81d4-55d01ed42022",
        document_code: "DOC-REV-41D275",
        original_filename: "rajasthan_pension_guidelines.pdf",
        source_name: "Social Security Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "READY_FOR_HUMAN_REVIEW",
        current_stage: "HUMAN_REVIEW",
        page_count: 10,
        file_size_bytes: 4096,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:27.892131+05:30",
        updated_at: "2026-09-26T21:43:27.892133+05:30",
      },
      {
        id: "8ed37fc6-0656-46a4-b013-3788dfc58a25",
        document_code: "DOC-REV-8ED37F",
        original_filename: "rajasthan_pension_guidelines.pdf",
        source_name: "Social Security Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "READY_FOR_HUMAN_REVIEW",
        current_stage: "HUMAN_REVIEW",
        page_count: 10,
        file_size_bytes: 4096,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:04.093103+05:30",
        updated_at: "2026-09-26T21:43:04.093107+05:30",
      },
      {
        id: "61120855-72a0-458f-a246-820526c7e970",
        document_code: "DOC-REV-611208",
        original_filename: "rajasthan_pension_guidelines.pdf",
        source_name: "Social Security Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "READY_FOR_HUMAN_REVIEW",
        current_stage: "HUMAN_REVIEW",
        page_count: 10,
        file_size_bytes: 4096,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:43:03.920529+05:30",
        updated_at: "2026-09-26T21:43:03.920541+05:30",
      },
      {
        id: "945f9e81-0569-47d5-9ee8-723bd5a05a55",
        document_code: "DOC-2026-D88F1637",
        original_filename: "table_doc_f29600.pdf",
        source_name: "Revenue Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "PUBLISHED",
        current_stage: "VERIFIED",
        page_count: 1,
        file_size_bytes: 3080,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:49:43.696761+05:30",
        updated_at: "2026-09-26T21:50:29.649257+05:30",
      },
      {
        id: "38b904fe-c315-4c00-8e4d-2d6cff246112",
        document_code: "DOC-2026-4392A6B1",
        original_filename: "mineru_fail_f24074.pdf",
        source_name: "Mines & Geology Dept",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "NORMALIZED",
        current_stage: "NORMALIZATION",
        page_count: 1,
        file_size_bytes: 1372538,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:52:30.908428+05:30",
        updated_at: "2026-09-26T21:52:31.302858+05:30",
      },
      {
        id: "2fe38e42-eff0-4a9d-9e3a-0831d887d8f1",
        document_code: "DOC-2026-9FBF8920",
        original_filename: "swasthya_2f5f92.pdf",
        source_name: "Medical Health & Family Welfare",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "NORMALIZED",
        current_stage: "NORMALIZATION",
        page_count: 1,
        file_size_bytes: 1372607,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:52:21.825447+05:30",
        updated_at: "2026-09-26T21:52:30.687834+05:30",
      },
      {
        id: "da831133-e0d6-43c2-842f-0bac4ad9aaea",
        document_code: "DOC-2026-7664507C",
        original_filename: "mixed_edbef0.pdf",
        source_name: "Energy & Renewable Department",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "PUBLISHED",
        current_stage: "VERIFIED",
        page_count: 3,
        file_size_bytes: 1716,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:51:28.139226+05:30",
        updated_at: "2026-09-26T21:52:21.693551+05:30",
      },
      {
        id: "a92f2297-4f1e-4c6d-8ad5-538ce7ab70c0",
        document_code: "DOC-2026-D9F4242B",
        original_filename: "scanned_37804c.pdf",
        source_name: "Cooperative Department",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "PUBLISHED",
        current_stage: "VERIFIED",
        page_count: 1,
        file_size_bytes: 518,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:50:53.641936+05:30",
        updated_at: "2026-09-26T21:51:28.065908+05:30",
      },
      {
        id: "013b7a3b-20ce-48f5-8943-078e3d4bd399",
        document_code: "DOC-2026-AED43BC4",
        original_filename: "gazette_aa015e.pdf",
        source_name: "Government Central Press Gazette",
        ingestion_method: "MANUAL_UPLOAD",
        processing_status: "NORMALIZED",
        current_stage: "NORMALIZATION",
        page_count: 11,
        file_size_bytes: 1377986,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T21:50:29.802322+05:30",
        updated_at: "2026-09-26T21:50:53.489725+05:30",
      },
      {
        id: "doc_pmkisan",
        document_code: "DOC-PMKISAN-CIRCULAR",
        original_filename: "PMKISAN_17th_Installment_Guidelines.pdf",
        source_name: "Ministry of Agriculture & Farmers Welfare",
        ingestion_method: "WEB_CRAWLER",
        processing_status: "HUMAN_VERIFIED",
        current_stage: "VERIFIED",
        page_count: 14,
        file_size_bytes: 1845000,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T20:00:00.000000+05:30",
        updated_at: "2026-09-26T21:00:00.000000+05:30",
      },
      {
        id: "doc_abpmjay",
        document_code: "DOC-ABPMJAY-GUIDELINES",
        original_filename: "NHA_ABPMJAY_Eligibility_Criteria_2024.pdf",
        source_name: "National Health Authority",
        ingestion_method: "WATCH_FOLDER",
        processing_status: "HUMAN_VERIFIED",
        current_stage: "VERIFIED",
        page_count: 28,
        file_size_bytes: 3120000,
        failure_reason: null,
        retry_valid: false,
        valid_retry_action: null,
        created_at: "2026-09-26T18:00:00.000000+05:30",
        updated_at: "2026-09-26T20:30:00.000000+05:30",
      },
    ],
    total: 86,
    page: 1,
    page_size: 25,
  };
}

export function getFallbackAdminConflicts(): AdminConflictListResponse {
  return {
    items: [
      {
        id: "conf_sample_1",
        conflict_type: "ELIGIBILITY_RULE_CONFLICT",
        severity: "CRITICAL",
        title: "Verification Issue: eligibility.family.definition",
        description: "Page 4 states entire enrolled Jan Aadhaar family is covered; amendment on page 9 notes sub-ceiling on married adult children.",
        scheme_id: "32de7937-11bb-4cb0-90c6-bd414550ef58",
        scheme_name: "Mukhyamantri Ayushman Arogya Yojana",
        document_id: "5bcd06f1-636b-4276-a227-da7dfa2cc9de",
        source_count: 1,
        status: "PENDING_OFFICER_REVIEW",
        link: "/admin/review/32de7937-11bb-4cb0-90c6-bd414550ef58",
        created_at: new Date().toISOString(),
      },
    ],
    total: 80,
    page: 1,
    page_size: 25,
  };
}

export function getFallbackAdminSources(): AdminSourceListResponse {
  const now = new Date();
  const sources = [
    {
      id: "src_1",
      source_url_id: "url_1",
      source_name: "myScheme - National Welfare Schemes Platform",
      url: "https://www.myscheme.gov.in/schemes",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_1",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 24).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 4).toISOString(),
      failure_count: 0,
      enabled: true,
    },
    {
      id: "src_2",
      source_url_id: "url_2",
      source_name: "Jan Soochna Portal - Public Welfare Schemes",
      url: "https://jansoochna.rajasthan.gov.in/Services/Schemes",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_1",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 12).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 2).toISOString(),
      failure_count: 0,
      enabled: true,
    },
    {
      id: "src_3",
      source_url_id: "url_3",
      source_name: "PM-KISAN Samman Nidhi Portal",
      url: "https://pmkisan.gov.in/BeneficiaryStatus_New.aspx",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_1",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 48).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 3).toISOString(),
      failure_count: 0,
      enabled: true,
    },
    {
      id: "src_4",
      source_url_id: "url_4",
      source_name: "National Scholarship Portal (NSP)",
      url: "https://scholarships.gov.in/public/schemeGuidelines",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_1",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 36).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 6).toISOString(),
      failure_count: 0,
      enabled: true,
    },
    {
      id: "src_5",
      source_url_id: "url_5",
      source_name: "Direct Benefit Transfer (DBT) Bharat",
      url: "https://dbtbharat.gov.in/page/schemelist",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_1",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 20).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 5).toISOString(),
      failure_count: 0,
      enabled: true,
    },
    {
      id: "src_6",
      source_url_id: "url_6",
      source_name: "PM Awas Yojana (PMAY-G / Housing)",
      url: "https://pmayg.nic.in/netiay/about-us.aspx",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_1",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 60).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 4).toISOString(),
      failure_count: 0,
      enabled: true,
    },
    {
      id: "src_7",
      source_url_id: "url_7",
      source_name: "RajSSP - Social Security Pension Portal",
      url: "https://rajssp.raj.nic.in/LoginContent/SchemeRules.aspx",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_1",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 18).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 2).toISOString(),
      failure_count: 0,
      enabled: true,
    },
    {
      id: "src_8",
      source_url_id: "url_8",
      source_name: "National Health Authority - Ayushman Bharat (PM-JAY)",
      url: "https://pmjay.gov.in/about/pmjay",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_1",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 30).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 4).toISOString(),
      failure_count: 0,
      enabled: true,
    },
    {
      id: "src_9",
      source_url_id: "url_9",
      source_name: "PM Vishwakarma & MSME Self-Employment",
      url: "https://pmvishwakarma.gov.in/Home/Schemes",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_2",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 72).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 8).toISOString(),
      failure_count: 0,
      enabled: true,
    },
    {
      id: "src_10",
      source_url_id: "url_10",
      source_name: "e-Mitra Rajasthan Citizen Services Gateway",
      url: "https://emitra.rajasthan.gov.in/services",
      authority_level: "OFFICIAL_PORTAL",
      priority_tier: "TIER_1",
      monitor_status: "MONITORED",
      last_check_at: now.toISOString(),
      last_change_at: new Date(Date.now() - 1000 * 3600 * 8).toISOString(),
      next_check_at: new Date(Date.now() + 1000 * 3600 * 2).toISOString(),
      failure_count: 0,
      enabled: true,
    },
  ];

  return {
    items: sources,
    total: sources.length,
    page: 1,
    page_size: 25,
  };
}

export function getFallbackWatchFolderStatus(): WatchFolderStatus {
  return {
    enabled: true,
    folder_path: "storage/watch_folder",
    pending_count: 0,
    pending_files: [],
    is_running: true,
  };
}

export function getFallbackReviewQueue(): ReviewQueueResponse {
  return {
    items: [
      {
        draft_id: "32de7937-11bb-4cb0-90c6-bd414550ef58",
        internal_scheme_code: "RJ-DRAFT-AA68443B",
        scheme_name: "Mukhyamantri Ayushman Arogya Yojana",
        department_name: "Medical, Health and Family Welfare Department",
        source_filename: "Raj_Sahay_Healthcare_Agent_Ready_v3_Audited.xlsx",
        document_id: "5bcd06f1-636b-4276-a227-da7dfa2cc9de",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 0,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 1,
        total_facts: 37,
        resolved_facts: 0,
        last_updated: "2026-09-26T21:43:29.000Z",
      },
      {
        draft_id: "bdbe3313-9686-4a0e-8723-42de6ab01bc0",
        internal_scheme_code: "RJ-REV-BDBE3313",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "7912570f-a84c-4e51-891b-6e425b0c16a3",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 0,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 5,
        resolved_facts: 8,
        last_updated: "2026-09-26T21:43:28.558Z",
      },
      {
        draft_id: "711b5499-5371-484c-b71d-ca8e7f38735d",
        internal_scheme_code: "RJ-REV-711B5499",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "6e2c45c8-2eff-48a8-a499-48058d2f2553",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 1,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 5,
        resolved_facts: 8,
        last_updated: "2026-09-26T21:43:28.167Z",
      },
      {
        draft_id: "33407d9a-dee9-4af0-abff-774ed0a16514",
        internal_scheme_code: "RJ-REV-33407D9A",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "6e2c45c8-2eff-48a8-a499-48058d2f2553",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 0,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 5,
        resolved_facts: 0,
        last_updated: "2026-09-26T21:43:28.107Z",
      },
      {
        draft_id: "dd5da4ee-f806-4652-9c30-90cb8b1f277f",
        internal_scheme_code: "RJ-REV-DD5DA4EE",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "04506837-0f6e-44c0-8fe7-0d0980c96b4f",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 0,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 5,
        resolved_facts: 0,
        last_updated: "2026-09-26T21:43:28.107Z",
      },
      {
        draft_id: "d1fa7497-d00b-40e8-bc54-dff88e2a8e92",
        internal_scheme_code: "RJ-REV-D1FA7497",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "fa047b50-4164-419f-aa58-94f74a191a2f",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 0,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 5,
        resolved_facts: 0,
        last_updated: "2026-09-26T21:43:28.040Z",
      },
      {
        draft_id: "09454c26-8fc8-41b5-82db-080be32c983b",
        internal_scheme_code: "RJ-REV-09454C26",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "41d275da-1f03-429e-81d4-55d01ed42022",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 0,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 5,
        resolved_facts: 0,
        last_updated: "2026-09-26T21:43:27.976Z",
      },
      {
        draft_id: "75653309-1711-4a83-88b5-e3f111496382",
        internal_scheme_code: "RJ-REV-75653309",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "8ed37fc6-0656-46a4-b013-3788dfc58a25",
        draft_status: "EVIDENCE_REVIEW_REQUIRED",
        review_status: "IN_PROGRESS",
        critical_issues: 22,
        contradicted_facts: 0,
        insufficient_facts: 8,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 8,
        resolved_facts: 1,
        last_updated: "2026-09-26T21:43:27.842Z",
      },
      {
        draft_id: "c36f1d17-6ff8-4f13-b485-789dce75d764",
        internal_scheme_code: "RJ-REV-C36F1D17",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "61120855-72a0-458f-a246-820526c7e970",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 0,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 5,
        resolved_facts: 1,
        last_updated: "2026-09-26T21:43:03.946Z",
      },
      {
        draft_id: "e3038635-c043-48d1-9334-e33d9183a101",
        internal_scheme_code: "RJ-REV-E3038635",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "e7235bba-5ba5-4174-97f9-dd6faa2b054e",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 0,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 5,
        resolved_facts: 1,
        last_updated: "2026-09-26T21:43:03.777Z",
      },
      {
        draft_id: "c53c7c30-38eb-4f41-9b35-822c2bd3d5ba",
        internal_scheme_code: "RJ-REV-C53C7C30",
        scheme_name: "राजस्थान वृद्धावस्था पेंशन योजना",
        department_name: "सामाजिक न्याय एवं अधिकारिता विभाग",
        source_filename: "rajasthan_pension_guidelines.pdf",
        document_id: "716d48a4-5207-450d-9b07-1d4eb3a3ff34",
        draft_status: "IN_HUMAN_REVIEW",
        review_status: "IN_PROGRESS",
        critical_issues: 0,
        contradicted_facts: 0,
        insufficient_facts: 0,
        ocr_risks: 0,
        conflicts: 0,
        total_facts: 5,
        resolved_facts: 0,
        last_updated: "2026-09-26T21:43:03.648Z",
      },
    ],
    total: 11,
    page: 1,
    page_size: 25,
  };
}

// Local in-memory store for fallback review session modifications
const fallbackReviewStore: Record<string, ReviewSessionDetail> = {};

export function getFallbackReviewDetail(draftId?: string): ReviewSessionDetail {
  const targetId =
    draftId && draftId !== "undefined"
      ? draftId
      : "32de7937-11bb-4cb0-90c6-bd414550ef58";

  if (fallbackReviewStore[targetId]) {
    return fallbackReviewStore[targetId];
  }

  const isPension =
    targetId.startsWith("RJ-REV") ||
    targetId.includes("pension") ||
    targetId === "bdbe3313-9686-4a0e-8723-42de6ab01bc0" ||
    targetId === "711b5499-5371-484c-b71d-ca8e7f38735d" ||
    targetId === "33407d9a-dee9-4af0-abff-774ed0a16514" ||
    targetId === "dd5da4ee-f806-4652-9c30-90cb8b1f277f" ||
    targetId === "d1fa7497-d00b-40e8-bc54-dff88e2a8e92" ||
    targetId === "09454c26-8fc8-41b5-82db-080be32c983b" ||
    targetId === "75653309-1711-4a83-88b5-e3f111496382" ||
    targetId === "c36f1d17-6ff8-4f13-b485-789dce75d764" ||
    targetId === "e3038635-c043-48d1-9334-e33d9183a101" ||
    targetId === "c53c7c30-38eb-4f41-9b35-822c2bd3d5ba";

  const schemeName = isPension
    ? "राजस्थान वृद्धावस्था पेंशन योजना"
    : "Mukhyamantri Ayushman Arogya Yojana";
  const deptName = isPension
    ? "सामाजिक न्याय एवं अधिकारिता विभाग"
    : "Medical, Health and Family Welfare Department";
  const internalCode = isPension
    ? `RJ-REV-${targetId.slice(0, 8).toUpperCase()}`
    : "RJ-DRAFT-AA68443B";
  const docId = isPension
    ? "6e2c45c8-2eff-48a8-a499-48058d2f2553"
    : "5bcd06f1-636b-4276-a227-da7dfa2cc9de";
  const sessionId = `session_${targetId.slice(0, 8)}`;

  const items: HumanReviewItem[] = isPension
    ? [
        {
          id: `item_${targetId}_1`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-PENS-001",
          field_path: "identity.official_name_raw",
          item_type: "IDENTITY",
          risk_level: "NORMAL",
          statement: "योजना का आधिकारिक नाम 'राजस्थान वृद्धावस्था पेंशन योजना' है।",
          original_value_json: { name: "राजस्थान वृद्धावस्था पेंशन योजना" },
          current_value_json: { name: "राजस्थान वृद्धावस्था पेंशन योजना" },
          raw_text: "राजस्थान वृद्धावस्था पेंशन योजना",
          evidence_refs: ["p1_b1"],
          evidence_text: "राजस्थान सरकार, सामाजिक न्याय एवं अधिकारिता विभाग - वृद्धावस्था पेंशन नियम",
          page_number: 1,
          block_id: "p1_b1",
          decision: "APPROVED",
          verification_result: "SUPPORTED",
          ocr_risk: false,
          reviewed_at: new Date().toISOString(),
          reviewed_by: "DEV_REVIEWER",
        },
        {
          id: `item_${targetId}_2`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-PENS-002",
          field_path: "eligibility.age.female_min",
          item_type: "ELIGIBILITY",
          risk_level: "NORMAL",
          statement: "महिला आवेदकों हेतु न्यूनतम आयु सीमा 55 वर्ष है।",
          original_value_json: { min_age: 55, gender: "FEMALE" },
          current_value_json: { min_age: 55, gender: "FEMALE" },
          raw_text: "महिला की आयु 55 वर्ष या अधिक हो।",
          evidence_refs: ["p2_b3"],
          evidence_text: "खंड 4(क): महिला आवेदक की न्यूनतम आयु 55 वर्ष पूर्ण होनी आवश्यक है।",
          page_number: 2,
          block_id: "p2_b3",
          decision: "PENDING",
          verification_result: "SUPPORTED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_3`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-PENS-003",
          field_path: "eligibility.age.male_min",
          item_type: "ELIGIBILITY",
          risk_level: "NORMAL",
          statement: "पुरुष आवेदकों हेतु न्यूनतम आयु सीमा 58 वर्ष है।",
          original_value_json: { min_age: 58, gender: "MALE" },
          current_value_json: { min_age: 58, gender: "MALE" },
          raw_text: "पुरुष की आयु 58 वर्ष या अधिक हो।",
          evidence_refs: ["p2_b4"],
          evidence_text: "खंड 4(ख): पुरुष आवेदक की न्यूनतम आयु 58 वर्ष अथवा अधिक हो।",
          page_number: 2,
          block_id: "p2_b4",
          decision: "PENDING",
          verification_result: "SUPPORTED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_4`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-PENS-004",
          field_path: "eligibility.income.max_annual",
          item_type: "ELIGIBILITY",
          risk_level: "HIGH",
          statement: "आवेदक की वार्षिक कुल पारिवारिक आय ₹48,000 से अधिक न हो। BPL परिवार हेतु आय सीमा में छूट।",
          original_value_json: { max_income: 48000, bpl_exempt: true },
          current_value_json: { max_income: 48000, bpl_exempt: true },
          raw_text: "पारिवारिक वार्षिक आय 48,000/- से अधिक न हो।",
          evidence_refs: ["p3_b1"],
          evidence_text: "खंड 5: संपूर्ण स्रोतों से वार्षिक आय 48,000 से कम होनी चाहिए; बीपीएल/अंत्योदय कार्डधारक छूट प्राप्त हैं।",
          page_number: 3,
          block_id: "p3_b1",
          decision: "PENDING",
          verification_result: "CONTRADICTED",
          verification_reason_code: "AMENDMENT_CEILING_REVISED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_5`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-PENS-005",
          field_path: "benefits.financial.monthly_pension",
          item_type: "BENEFIT",
          risk_level: "NORMAL",
          statement: "मासिक पेंशन राशि ₹1,000 से ₹1,500 आयु वर्ग के आधार पर प्रत्यक्ष बैंक खाते (DBT) में देय।",
          original_value_json: { amount: 1000, currency: "INR", frequency: "MONTHLY" },
          current_value_json: { amount: 1000, currency: "INR", frequency: "MONTHLY" },
          raw_text: "न्यूनतम ₹1,000 प्रतिमाह पेंशन सीधे बैंक खाते में हस्तांतरित होगी।",
          evidence_refs: ["p3_b7"],
          evidence_text: "राजस्थान न्यूनतम आय गारंटी अधिनियम के तहत 15% वार्षिक वृद्धि सहित ₹1000 प्रतिमाह न्यूनतम।",
          page_number: 3,
          block_id: "p3_b7",
          decision: "APPROVED",
          verification_result: "SUPPORTED",
          ocr_risk: false,
          reviewed_at: new Date().toISOString(),
          reviewed_by: "DEV_REVIEWER",
        },
        {
          id: `item_${targetId}_6`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-PENS-006",
          field_path: "exclusions.pensioners",
          item_type: "EXCLUSION",
          risk_level: "NORMAL",
          statement: "केंद्र या राज्य सरकार से अन्य किसी प्रकार की नियमित सेवा पेंशन प्राप्तकर्ता अपात्र हैं।",
          original_value_json: { excluded: "Recipients of government civil/service pensions" },
          current_value_json: { excluded: "Recipients of government civil/service pensions" },
          raw_text: "शासकीय पेंशनभोगी परिवार इस योजना हेतु अपात्र होंगे।",
          evidence_refs: ["p4_b2"],
          evidence_text: "खंड 7(अ): यदि आवेदक किसी अन्य सरकारी स्रोत से पेंशन प्राप्त कर रहा है तो वह इस योजना का पात्र नहीं होगा।",
          page_number: 4,
          block_id: "p4_b2",
          decision: "PENDING",
          verification_result: "SUPPORTED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_7`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-PENS-007",
          field_path: "documents.required.janaadhaar",
          item_type: "DOCUMENT",
          risk_level: "NORMAL",
          statement: "जनाधार कार्ड / आधार कार्ड तथा बैंक खाता विवरण अनिवार्य दस्तावेज हैं।",
          original_value_json: { documents: ["Jan Aadhaar Card", "Aadhaar Card", "Bank Passbook"], mandatory: true },
          current_value_json: { documents: ["Jan Aadhaar Card", "Aadhaar Card", "Bank Passbook"], mandatory: true },
          raw_text: "जनाधार पोर्टल के माध्यम से ऑनलाइन सत्यापन अनिवार्य।",
          evidence_refs: ["p5_b1"],
          evidence_text: "खंड 9: आवेदन हेतु जनाधार संख्या एवं बैंक खाते का एक्टिव होना अनिवार्य।",
          page_number: 5,
          block_id: "p5_b1",
          decision: "PENDING",
          verification_result: "SUPPORTED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_8`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-PENS-008",
          field_path: "application.process.channels",
          item_type: "APPLICATION",
          risk_level: "NORMAL",
          statement: "ई-मित्र केंद्र (E-Mitra) या जन सूचना पोर्टल (SSO) के माध्यम से ऑनलाइन आवेदन प्रक्रिया।",
          original_value_json: { channels: ["EMITRA", "SSO_ONLINE"], portal: "https://ssp.rajasthan.gov.in" },
          current_value_json: { channels: ["EMITRA", "SSO_ONLINE"], portal: "https://ssp.rajasthan.gov.in" },
          raw_text: "आवेदन निकटतम ई-मित्र अथवा ऑनलाइन एसएसपी पोर्टल द्वारा।",
          evidence_refs: ["p6_b2"],
          evidence_text: "प्रक्रिया: नागरिक स्वयं अथवा ई-मित्र के माध्यम से जनाधार डेटा द्वारा आवेदन कर सकते हैं।",
          page_number: 6,
          block_id: "p6_b2",
          decision: "EDITED",
          edit_reason: "Verified official URL update to ssp.rajasthan.gov.in",
          reviewer_comment: "Updated application portal link to match current SSP system.",
          verification_result: "SUPPORTED",
          ocr_risk: false,
          reviewed_at: new Date().toISOString(),
          reviewed_by: "DEV_REVIEWER",
        },
      ]
    : [
        {
          id: `item_${targetId}_1`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-AA68443B-001",
          field_path: "identity.official_name_raw",
          item_type: "IDENTITY",
          risk_level: "NORMAL",
          statement: "Official scheme name is 'Mukhyamantri Ayushman Arogya Yojana'.",
          original_value_json: { name: "Mukhyamantri Ayushman Arogya Yojana" },
          current_value_json: { name: "Mukhyamantri Ayushman Arogya Yojana" },
          raw_text: "Mukhyamantri Ayushman Arogya Yojana",
          evidence_refs: ["p1_b1"],
          evidence_text: "Official scheme notification and operational guidelines for Ayushman Arogya Yojana.",
          page_number: 1,
          block_id: "p1_b1",
          decision: "APPROVED",
          verification_result: "SUPPORTED",
          ocr_risk: false,
          reviewed_at: new Date().toISOString(),
          reviewed_by: "DEV_REVIEWER",
        },
        {
          id: `item_${targetId}_2`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-AA68443B-002",
          field_path: "eligibility.residence.state",
          item_type: "ELIGIBILITY",
          risk_level: "NORMAL",
          statement: "Applicant must be a permanent resident of Rajasthan or enrolled in Jan Aadhaar database.",
          original_value_json: { state_criteria: "Rajasthan permanent residents / Jan Aadhaar enrolled" },
          current_value_json: { state_criteria: "Rajasthan permanent residents / Jan Aadhaar enrolled" },
          raw_text: "All families registered under Jan Aadhaar card in Rajasthan.",
          evidence_refs: ["p2_b1"],
          evidence_text: "Clause 3: All families enrolled under Jan Aadhaar scheme are covered under the entitlement criteria.",
          page_number: 2,
          block_id: "p2_b1",
          decision: "APPROVED",
          verification_result: "SUPPORTED",
          ocr_risk: false,
          reviewed_at: new Date().toISOString(),
          reviewed_by: "DEV_REVIEWER",
        },
        {
          id: `item_${targetId}_3`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-AA68443B-003",
          field_path: "eligibility.family.definition",
          item_type: "ELIGIBILITY",
          risk_level: "HIGH",
          statement: "Family unit definition for secondary package entitlement.",
          original_value_json: { family_criteria: "Listed in Jan Aadhaar database" },
          current_value_json: { family_criteria: "Listed in Jan Aadhaar database" },
          raw_text: "Clause 4 specifies coverage for all members; amendment indicates separate unit definition for married children.",
          evidence_refs: ["p4_b2"],
          evidence_text: "Page 4 indicates coverage for all enrolled members; amendment on page 9 notes sub-ceiling on non-dependents.",
          page_number: 4,
          block_id: "p4_b2",
          decision: "PENDING",
          verification_result: "CONTRADICTED",
          verification_reason_code: "RULE_AMENDMENT_CONFLICT",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_4`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-AA68443B-004",
          field_path: "benefits.cashless_cover.annual_sum_insured",
          item_type: "BENEFIT",
          risk_level: "NORMAL",
          statement: "Annual cashless health cover up to ₹25,00,000 per family per year in empanelled hospitals.",
          original_value_json: { annual_limit: 2500000, currency: "INR", type: "CASHLESS_HOSPITALIZATION" },
          current_value_json: { annual_limit: 2500000, currency: "INR", type: "CASHLESS_HOSPITALIZATION" },
          raw_text: "Cashless treatment package up to Rs 25 Lakhs per family per year in empanelled hospitals.",
          evidence_refs: ["p5_b1"],
          evidence_text: "Section 5.1: Cashless medical treatment package up to 25 Lakhs per family per annum.",
          page_number: 5,
          block_id: "p5_b1",
          decision: "PENDING",
          verification_result: "SUPPORTED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_5`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-AA68443B-005",
          field_path: "benefits.accidental_insurance.cover_limit",
          item_type: "BENEFIT",
          risk_level: "LOW",
          statement: "Accidental death and permanent disability insurance cover up to ₹10,00,000.",
          original_value_json: { accidental_cover: 1000000, currency: "INR" },
          current_value_json: { accidental_cover: 1000000, currency: "INR" },
          raw_text: "Accidental insurance cover up to Rs 10 Lakhs.",
          evidence_refs: ["p6_b3"],
          evidence_text: "Accidental death or permanent total disability provides financial relief up to Rs. 10 Lakhs.",
          page_number: 6,
          block_id: "p6_b3",
          decision: "PENDING",
          verification_result: "SUPPORTED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_6`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-AA68443B-006",
          field_path: "exclusions.government_employees",
          item_type: "EXCLUSION",
          risk_level: "NORMAL",
          statement: "Government employees covered under RGHS (Rajasthan Government Health Scheme) excluded.",
          original_value_json: { excluded_category: "State govt regular employees covered under RGHS" },
          current_value_json: { excluded_category: "State govt regular employees covered under RGHS" },
          raw_text: "Employees eligible for RGHS are not eligible under Ayushman Arogya Yojana.",
          evidence_refs: ["p7_b1"],
          evidence_text: "Clause 7.2: Regular employees and pensioners covered under RGHS are excluded from this scheme.",
          page_number: 7,
          block_id: "p7_b1",
          decision: "PENDING",
          verification_result: "SUPPORTED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_7`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-AA68443B-007",
          field_path: "documents.required.jan_aadhaar",
          item_type: "DOCUMENT",
          risk_level: "NORMAL",
          statement: "Jan Aadhaar Card or Jan Aadhaar Enrollment Slip mandatory for identification.",
          original_value_json: { document_name: "Jan Aadhaar Card / Slip", mandatory: true },
          current_value_json: { document_name: "Jan Aadhaar Card / Slip", mandatory: true },
          raw_text: "Jan Aadhaar enrollment slip or card required at hospital registration.",
          evidence_refs: ["p2_b4"],
          evidence_text: "Hospital registration requires verification of identity via Jan Aadhaar or Aadhaar biometric / OTP.",
          page_number: 2,
          block_id: "p2_b4",
          decision: "PENDING",
          verification_result: "SUPPORTED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_8`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-AA68443B-008",
          field_path: "documents.required.aadhaar",
          item_type: "DOCUMENT",
          risk_level: "NORMAL",
          statement: "Aadhaar card of patient / family head.",
          original_value_json: { document_name: "Aadhaar Card", mandatory: true },
          current_value_json: { document_name: "Aadhaar Card", mandatory: true },
          raw_text: "Aadhaar verification required at the time of hospital admission.",
          evidence_refs: ["p2_b5"],
          evidence_text: "Aadhaar authentication required at hospital admission counter.",
          page_number: 2,
          block_id: "p2_b5",
          decision: "PENDING",
          verification_result: "SUPPORTED",
          ocr_risk: false,
        },
        {
          id: `item_${targetId}_9`,
          review_session_id: sessionId,
          scheme_draft_id: targetId,
          fact_id: "FACT-AA68443B-009",
          field_path: "application.process.online_portal",
          item_type: "APPLICATION",
          risk_level: "NORMAL",
          statement: "Registration via SSO Portal (sso.rajasthan.gov.in) or E-Mitra kiosk.",
          original_value_json: { channels: ["ONLINE_SSO", "EMITRA"], portal: "https://health.rajasthan.gov.in" },
          current_value_json: { channels: ["ONLINE_SSO", "EMITRA"], portal: "https://health.rajasthan.gov.in" },
          raw_text: "Citizen can apply directly on SSO or visit nearest E-Mitra kiosk.",
          evidence_refs: ["p8_b2"],
          evidence_text: "Online registration available at SSO portal or offline through E-Mitra network.",
          page_number: 8,
          block_id: "p8_b2",
          decision: "EDITED",
          edit_reason: "Added explicit E-Mitra kiosk support flag",
          reviewer_comment: "Verified that both SSO and E-Mitra channels are active.",
          verification_result: "SUPPORTED",
          ocr_risk: false,
          reviewed_at: new Date().toISOString(),
          reviewed_by: "DEV_REVIEWER",
        },
      ];

  const approved = items.filter((i) => i.decision === "APPROVED").length;
  const edited = items.filter((i) => i.decision === "EDITED").length;
  const rejected = items.filter((i) => i.decision === "REJECTED").length;
  const not_applicable = items.filter((i) => i.decision === "NOT_APPLICABLE").length;
  const pending = items.filter((i) => i.decision === "PENDING").length;

  const conflicts: ConflictItem[] = [
    {
      conflict_id: `CONF-${targetId.slice(0, 8)}-01`,
      field: isPension ? "eligibility.income.max_annual" : "eligibility.family.definition",
      status: "UNRESOLVED",
      explanation: isPension
        ? "खंड 5 में पारिवारिक आय ₹48,000 अंकित है जबकि हालिया परिपत्र में यह सीमा ₹60,000 संशोधित की गई है।"
        : "Page 4 states entire registered Jan Aadhaar family is covered; Page 9 indicates sub-ceiling on married sons.",
      values: [
        {
          value: isPension ? "वार्षिक आय सीमा ₹48,000" : "All Jan Aadhaar family members covered unconditionally",
          page_number: isPension ? 3 : 4,
          text_snippet: isPension
            ? "खंड 5: संपूर्ण स्रोतों से वार्षिक आय ₹48,000 से कम होनी चाहिए।"
            : "All family members enumerated in the Jan Aadhaar family card get full cashless entitlement.",
          source_type: "PRIMARY_GUIDELINE",
        },
        {
          value: isPension ? "संशोधित सीमा ₹60,000 (परिपत्र 2024)" : "Excludes married children maintaining separate ration units",
          page_number: isPension ? 6 : 9,
          text_snippet: isPension
            ? "संशोधन: ग्रामीण एवं शहरी क्षेत्र हेतु अधिकतम वार्षिक आय सीमा ₹60,000 निर्धारित की गई है।"
            : "Married adult children who have established independent households shall constitute a distinct entitlement unit.",
          source_type: "SUBSEQUENT_AMENDMENT",
        },
      ],
    },
  ];

  const audit_events: ReviewAuditEvent[] = [
    {
      id: `audit_${targetId}_1`,
      review_session_id: sessionId,
      scheme_draft_id: targetId,
      reviewer_id: "DEV_REVIEWER",
      action_type: "DECISION_EDITED",
      field_path: isPension ? "application.process.channels" : "application.process.online_portal",
      reason: "Verified official channel and portal URLs.",
      created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    },
    {
      id: `audit_${targetId}_2`,
      review_session_id: sessionId,
      scheme_draft_id: targetId,
      reviewer_id: "SYSTEM",
      action_type: "VERIFICATION_COMPLETED",
      reason: "Automated evidence verification and fact cross-matching executed.",
      created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    },
    {
      id: `audit_${targetId}_3`,
      review_session_id: sessionId,
      scheme_draft_id: targetId,
      reviewer_id: "SYSTEM",
      action_type: "SESSION_INITIALIZED",
      reason: "Human review session opened from ingestion pipeline.",
      created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    },
  ];

  const detail: ReviewSessionDetail = {
    session_id: sessionId,
    scheme_draft_id: targetId,
    document_id: docId,
    internal_scheme_code: internalCode,
    scheme_name: schemeName,
    department_name: deptName,
    reviewer_id: "DEV_REVIEWER",
    session_status: "IN_PROGRESS",
    draft_status: "IN_HUMAN_REVIEW",
    review_version: 1,
    canonical_artifact_sha256: "4b29684ae07d2926e65761fbf2eff369dc30fc54f85b507c8cf2c9b73f112842",
    is_stale: false,
    notes: "Human verification in progress for statutory welfare benefits and citizen criteria.",
    summary: {
      total_items: items.length,
      approved,
      edited,
      rejected,
      not_applicable,
      pending,
    },
    items,
    conflicts,
    validation_summary: {
      total_checks: 42,
      passed: 40,
      warnings: 2,
      errors: 0,
      blockers: 0,
    },
    verification_summary: {
      total_facts: items.length,
      supported: items.filter((i) => i.verification_result === "SUPPORTED").length,
      contradicted: items.filter((i) => i.verification_result === "CONTRADICTED").length,
      not_enough_evidence: 0,
    },
    audit_events,
    started_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    completed_at: null,
  };

  fallbackReviewStore[targetId] = detail;
  return detail;
}

export function updateFallbackReviewDecision(
  itemId: string,
  payload: ItemDecisionPayload
): HumanReviewItem {
  for (const detail of Object.values(fallbackReviewStore)) {
    const item = detail.items.find((i) => i.id === itemId);
    if (item) {
      item.decision = payload.decision;
      if (payload.reviewer_comment !== undefined) item.reviewer_comment = payload.reviewer_comment;
      if (payload.edit_reason !== undefined) item.edit_reason = payload.edit_reason;
      if (payload.override_reason !== undefined) item.override_reason = payload.override_reason;
      if (payload.edit_value !== undefined) item.current_value_json = payload.edit_value;
      item.reviewed_at = new Date().toISOString();
      item.reviewed_by = "DEV_REVIEWER";

      // Recalculate summary
      detail.summary = {
        total_items: detail.items.length,
        approved: detail.items.filter((i) => i.decision === "APPROVED").length,
        edited: detail.items.filter((i) => i.decision === "EDITED").length,
        rejected: detail.items.filter((i) => i.decision === "REJECTED").length,
        not_applicable: detail.items.filter((i) => i.decision === "NOT_APPLICABLE").length,
        pending: detail.items.filter((i) => i.decision === "PENDING").length,
      };

      // Add audit event
      detail.audit_events.unshift({
        id: `audit_${Date.now()}`,
        review_session_id: detail.session_id,
        scheme_draft_id: detail.scheme_draft_id,
        reviewer_id: "DEV_REVIEWER",
        action_type: `DECISION_${payload.decision}`,
        field_path: item.field_path,
        item_id: item.id,
        reason: payload.reviewer_comment || payload.edit_reason || payload.override_reason || null,
        created_at: new Date().toISOString(),
      });

      return item;
    }
  }

  // Return a generic fallback item if not found
  return {
    id: itemId,
    review_session_id: "session_fallback",
    scheme_draft_id: "32de7937-11bb-4cb0-90c6-bd414550ef58",
    fact_id: "FACT-FALLBACK",
    field_path: "field.updated",
    item_type: "ELIGIBILITY",
    risk_level: "NORMAL",
    statement: "Decision recorded.",
    decision: payload.decision,
    reviewer_comment: payload.reviewer_comment,
    ocr_risk: false,
    evidence_refs: [],
    reviewed_at: new Date().toISOString(),
    reviewed_by: "DEV_REVIEWER",
  };
}

export function resolveFallbackConflict(
  draftId: string,
  conflictId: string,
  payload: ConflictResolutionPayload
): any {
  const detail = fallbackReviewStore[draftId] || getFallbackReviewDetail(draftId);
  const conflict = detail.conflicts.find((c) => c.conflict_id === conflictId);
  if (conflict) {
    conflict.status = "RESOLVED";
  }
  detail.audit_events.unshift({
    id: `audit_${Date.now()}`,
    review_session_id: detail.session_id,
    scheme_draft_id: detail.scheme_draft_id,
    reviewer_id: "DEV_REVIEWER",
    action_type: "CONFLICT_RESOLVED",
    reason: `Conflict ${conflictId} resolved with choice: ${payload.choice}`,
    created_at: new Date().toISOString(),
  });
  return { success: true, conflict_id: conflictId, resolution: payload.choice };
}

export function completeFallbackReview(draftId: string, notes?: string): any {
  const detail = fallbackReviewStore[draftId] || getFallbackReviewDetail(draftId);
  detail.session_status = "COMPLETED";
  detail.draft_status = "HUMAN_VERIFIED";
  detail.completed_at = new Date().toISOString();
  if (notes) detail.notes = notes;
  detail.audit_events.unshift({
    id: `audit_${Date.now()}`,
    review_session_id: detail.session_id,
    scheme_draft_id: detail.scheme_draft_id,
    reviewer_id: "DEV_REVIEWER",
    action_type: "DECISION_COMPLETE",
    reason: notes || "Review session completed and sealed.",
    created_at: new Date().toISOString(),
  });
  return { success: true, message: "Scheme draft successfully verified and sealed!" };
}

export function rejectFallbackReview(draftId: string, reason: string): any {
  const detail = fallbackReviewStore[draftId] || getFallbackReviewDetail(draftId);
  detail.session_status = "REJECTED";
  detail.draft_status = "HUMAN_REJECTED";
  detail.notes = reason;
  detail.audit_events.unshift({
    id: `audit_${Date.now()}`,
    review_session_id: detail.session_id,
    scheme_draft_id: detail.scheme_draft_id,
    reviewer_id: "DEV_REVIEWER",
    action_type: "DECISION_REJECT",
    reason,
    created_at: new Date().toISOString(),
  });
  return { success: true, message: "Scheme draft rejected." };
}

export function reopenFallbackReview(draftId: string, reason: string): any {
  const detail = fallbackReviewStore[draftId] || getFallbackReviewDetail(draftId);
  detail.session_status = "IN_PROGRESS";
  detail.draft_status = "IN_HUMAN_REVIEW";
  detail.review_version = (detail.review_version || 1) + 1;
  detail.audit_events.unshift({
    id: `audit_${Date.now()}`,
    review_session_id: detail.session_id,
    scheme_draft_id: detail.scheme_draft_id,
    reviewer_id: "DEV_REVIEWER",
    action_type: "REVIEW_REOPENED",
    reason,
    created_at: new Date().toISOString(),
  });
  return { success: true, message: "Review session reopened." };
}

export function getFallbackSchemeDetail(schemeId: string): SchemeDetailResponse {
  return {
    id: schemeId,
    scheme_code: "IND-SCHEME",
    name_en: "Government Welfare Scheme",
    name_hi: "जनकल्याणकारी योजना",
    department_id: "dept_01",
    department_name: "Department of Social Justice",
    category_id: "cat_01",
    category_name: "Social Welfare",
    short_description: "All-India welfare program for eligible citizens.",
    status: "ACTIVE",
    jurisdiction: "ALL_INDIA",
    scheme_origin: "CENTRAL",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    canonical_data: {
      scheme_identity: {
        name: { en: "Government Welfare Scheme", hi: "जनकल्याणकारी योजना" },
        scheme_code: "IND-SCHEME",
      },
      benefits: [
        {
          type: "FINANCIAL",
          amount: 6000,
          currency: "INR",
          frequency: "ANNUAL",
          description: "Direct benefit transfer into bank account.",
        },
      ],
      eligibility: {
        simple_fields: { min_age: 18 },
        conditions: [],
        exclusions: [],
      },
      required_documents: [
        {
          document_id: "DOC-AADHAAR",
          document_type: "AADHAAR",
          name_raw: "Aadhaar Card",
          mandatory: true,
        },
      ],
      application: {
        channels: ["ONLINE", "OFFLINE"],
        portal_url: "https://www.india.gov.in",
        steps: ["Visit official portal", "Submit identity details", "Verify bank account"],
      },
    },
  };
}
