"""
JanSetu - Day 22: Speech-to-Text Benchmark Schemas and Data Models.

Defines typed representations for:
- STT Provider transcription results (with raw text immutability)
- Benchmark sample annotations and critical entity targets
- Per-sample evaluation results (WER, CER, entity accuracies, latency)
- Benchmark run configurations, summaries, and critical failure reports
"""

from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AudioNoiseLevel(str, Enum):
    CLEAN = "CLEAN"
    LIGHT_NOISE = "LIGHT_NOISE"
    MODERATE_NOISE = "MODERATE_NOISE"


class BenchmarkCategory(str, Enum):
    HINDI_CLEAN = "HINDI_CLEAN"
    HINDI_NOISY = "HINDI_NOISY"
    RAJASTHANI_DIALECT_STYLE = "RAJASTHANI_DIALECT_STYLE"
    CODE_MIXED = "CODE_MIXED"
    SHORT_ANSWER = "SHORT_ANSWER"
    LONG_MULTI_ENTITY = "LONG_MULTI_ENTITY"
    AGE = "AGE"
    INCOME = "INCOME"
    DISTRICT = "DISTRICT"
    NEGATION = "NEGATION"
    GOVERNMENT_TERMS = "GOVERNMENT_TERMS"


class STTSegment(BaseModel):
    """Segment-level transcription timing and confidence details."""
    id: int
    start_seconds: float
    end_seconds: float
    text: str
    avg_logprob: Optional[float] = None
    no_speech_prob: Optional[float] = None


class STTResult(BaseModel):
    """
    Immutable raw transcription result returned by an STT Provider.
    Critical Invariant: Raw text is stored exactly as generated by the model.
    """
    raw_text: str = Field(..., description="Exact verbatim text output from the model")
    text: str = Field(..., description="Verbatim text (identical to raw_text upon generation)")
    language: str = Field(default="hi", description="Detected or specified ISO language code")
    duration_seconds: float = Field(..., description="Input audio duration in seconds")
    inference_ms: float = Field(..., description="Total model inference latency in milliseconds")
    provider: str = Field(..., description="Provider identifier (e.g. whisper, indic_asr)")
    model: str = Field(..., description="Model name or checkpoint path")
    device: str = Field(default="cpu", description="Inference device (cpu, cuda)")
    precision: str = Field(default="fp32", description="Inference precision (int8, fp16, fp32)")
    segments: List[STTSegment] = Field(default_factory=list, description="Timestamped segments if available")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Provider-specific diagnostic metadata")


class CriticalEntityTarget(BaseModel):
    """Expected critical field values for eligibility determination."""
    age: Optional[int] = None
    family_income: Optional[int] = None
    income_frequency: Optional[str] = None  # YEARLY, MONTHLY
    district: Optional[str] = None
    occupation: Optional[str] = None
    bpl_status: Optional[bool] = None
    disability_status: Optional[bool] = None
    land_holding_acres: Optional[float] = None
    education_level: Optional[str] = None
    scheme_name: Optional[str] = None
    negation: Optional[bool] = None  # Explicit negation asserted (e.g., "नहीं हूँ")


class BenchmarkSample(BaseModel):
    """Annotated benchmark dataset sample entry."""
    id: str = Field(..., description="Unique sample identifier (e.g. HI-CLEAN-001)")
    audio_file: str = Field(..., description="Relative path to audio file in dataset directory")
    reference: str = Field(..., description="Verbatim reference ground-truth transcript")
    language: str = Field(default="hi", description="Expected language/dialect code")
    category: BenchmarkCategory = Field(..., description="Primary test category")
    secondary_categories: List[BenchmarkCategory] = Field(default_factory=list)
    noise_level: AudioNoiseLevel = Field(default=AudioNoiseLevel.CLEAN)
    speech_rate: str = Field(default="normal")  # slow, normal, fast
    speaker_group: Optional[str] = None
    is_short_answer: bool = Field(default=False)
    entities: CriticalEntityTarget = Field(default_factory=CriticalEntityTarget)
    notes: Optional[str] = None


class FieldMatchResult(BaseModel):
    """Evaluation result for a single critical field."""
    field_name: str
    expected: Any
    predicted: Any
    is_correct: bool
    is_critical_failure: bool = False
    details: Optional[str] = None


class SampleResult(BaseModel):
    """Comprehensive evaluation result for a single benchmark utterance."""
    sample_id: str
    audio_duration_seconds: float
    inference_ms: float
    real_time_factor: float  # RTF = inference_seconds / audio_duration_seconds
    reference_raw: str
    prediction_raw: str
    reference_normalized: str
    prediction_normalized: str
    wer: float = Field(..., ge=0.0, description="Word Error Rate (0.0 to 1.0+)")
    cer: float = Field(..., ge=0.0, description="Character Error Rate (0.0 to 1.0+)")
    category: str
    noise_level: str
    critical_entities: Dict[str, FieldMatchResult] = Field(default_factory=dict)
    all_critical_entities_correct: bool = True
    has_critical_failure: bool = False
    error: Optional[str] = None


class CriticalFailureItem(BaseModel):
    """Detailed record of an eligibility-critical transcription failure."""
    sample_id: str
    category: str
    field_name: str
    expected_value: Any
    predicted_value: Any
    reference_text: str
    predicted_text: str
    reason: str


class CategoryMetricSummary(BaseModel):
    """Aggregated metrics for a specific test category."""
    category: str
    sample_count: int
    avg_wer: float
    avg_cer: float
    avg_inference_ms: float
    avg_rtf: float
    all_entities_accuracy: float
    critical_failures_count: int


class BenchmarkSummary(BaseModel):
    """Overall benchmark evaluation summary across all samples."""
    benchmark_run_id: str
    provider: str
    model: str
    device: str
    precision: str
    dataset_version: str
    benchmark_version: str
    timestamp: datetime
    total_samples: int
    successful_samples: int
    failed_samples: int
    overall_wer: float
    overall_cer: float
    avg_inference_ms: float
    avg_rtf: float
    age_accuracy: float
    income_accuracy: float
    district_accuracy: float
    negation_accuracy: float
    government_term_accuracy: float
    all_critical_entities_accuracy: float
    total_critical_failures: int
    categories: Dict[str, CategoryMetricSummary] = Field(default_factory=dict)
    model_load_time_seconds: float = 0.0
    ram_usage_mb: Optional[float] = None
    vram_usage_mb: Optional[float] = None
    disk_footprint_mb: Optional[float] = None
